apiVersion: v1
kind: Service
metadata:
  name: {{ include "https-wrench.fullname" . }}
  labels:
    {{- include "https-wrench.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    {{- include "https-wrench.selectorLabels" . | nindent 4 }}
